version: 2
updates:
  - package-ecosystem: gomod
    directory: /tests/interop/Pion
    schedule:
      interval: weekly
    groups:
      peer:
        patterns: ['*']
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    groups:
      all:
        patterns: ['*']
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
