changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Features
      labels: [enhancement]
    - title: Fixes
      labels: [bug]
    - title: Dependencies and tooling
      labels: [dependencies]
    - title: Other changes
      labels: ['*']
