<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>true</IsAotCompatible>
    <SuppressTrimAnalysisWarnings>false</SuppressTrimAnalysisWarnings>
    <TrimmerSingleWarn>false</TrimmerSingleWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../libs/WebRTC/WebRTC.csproj" />
    <TrimmerRootAssembly Include="tryAGI.WebRTC" />
  </ItemGroup>
<ItemGroup>
    <Compile Include="../WebRTC.IntegrationTests/TurnFixture.cs" Link="TurnFixture.cs" />
  </ItemGroup>
</Project>
