<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="tryAGI.WebRTC" Version="[0.2.8]" />
    <Compile Include="../WebRTC.IntegrationTests/PeerSctpRoleTests.cs" Link="PeerSctpRoleTests.cs" />
    <Compile Include="../WebRTC.IntegrationTests/BundleTransportTests.cs" Link="BundleTransportTests.cs" />
  </ItemGroup>
</Project>
