<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../libs/WebRTC/WebRTC.csproj" />
  </ItemGroup>
<ItemGroup>
    <Compile Include="../WebRTC.ProtocolTests/VideoTests.cs" Link="VideoTests.cs" />
  </ItemGroup>
<ItemGroup><Compile Include="../WebRTC.ProtocolTests/SdpVideoTests.cs" Link="SdpVideoTests.cs" /></ItemGroup>
<ItemGroup><Compile Include="../WebRTC.ProtocolTests/RtcpTests.cs" Link="RtcpProtocolTests.cs" /></ItemGroup>
<ItemGroup><Compile Include="../WebRTC.ProtocolTests/SdpRtcpTests.cs" Link="SdpRtcpTests.cs" /></ItemGroup>
</Project>
