<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../libs/WebRTC/WebRTC.csproj" />
  </ItemGroup>
<ItemGroup>
    <Compile Include="../WebRTC.ProtocolTests/VideoTests.cs" Link="VideoTests.cs" />
  </ItemGroup>
</Project>
