// Copyright (c) 2026 tryAGI and contributors. Licensed under MIT.
// Independently authored harness using Pion's public SRTP API.
package main

import (
	"encoding/hex"
	"encoding/json"
	"io"
	"log"
	"net/http"

	"github.com/pion/rtp/codecs"
	"github.com/pion/srtp/v3"
)

type cryptoRequest struct {
	Profile  uint16   `json:"profile"`
	Key      string   `json:"key"`
	Salt     string   `json:"salt"`
	Rtcp     bool     `json:"rtcp"`
	Decrypt  bool     `json:"decrypt"`
	AuthOnly bool     `json:"authOnly"`
	Packets  []string `json:"packets"`
}

func registerSrtp(mux *http.ServeMux) {
	slots := make(chan struct{}, 4)
	// Bounded loopback test-only public payloader API. Authored synthetic inputs, no codec implementation copied.
	mux.HandleFunc("POST /video-payload", func(w http.ResponseWriter, r *http.Request) {
		select {
		case slots <- struct{}{}:
		default:
			http.Error(w, "limit", 429)
			return
		}
		defer func() { <-slots }()
		var request struct {
			Codec string `json:"codec"`
			Frame string `json:"frame"`
			Mtu   uint16 `json:"mtu"`
		}
		decoder := json.NewDecoder(http.MaxBytesReader(w, r.Body, 70000))
		decoder.DisallowUnknownFields()
		if decoder.Decode(&request) != nil || request.Mtu < 64 || request.Mtu > 1100 || len(request.Frame) > 65536 {
			http.Error(w, "invalid frame", 400)
			return
		}
		frame, err := hex.DecodeString(request.Frame)
		if err != nil || len(frame) == 0 {
			http.Error(w, "invalid frame", 400)
			return
		}
		var payloads [][]byte
		switch request.Codec {
		case "H264":
			p := &codecs.H264Payloader{}
			payloads = p.Payload(request.Mtu, frame)
		case "Vp8":
			p := &codecs.VP8Payloader{}
			payloads = p.Payload(request.Mtu, frame)
		default:
			http.Error(w, "unsupported codec", 400)
			return
		}
		if len(payloads) == 0 || len(payloads) > 512 {
			http.Error(w, "payload limit", 400)
			return
		}
		result := make([]string, len(payloads))
		for i, p := range payloads {
			result[i] = hex.EncodeToString(p)
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(result)
	})
	mux.HandleFunc("POST /srtp", func(w http.ResponseWriter, r *http.Request) {
		select {
		case slots <- struct{}{}:
		default:
			http.Error(w, "limit", 429)
			return
		}
		defer func() { <-slots }()
		var request cryptoRequest
		decoder := json.NewDecoder(io.LimitReader(r.Body, 256*1024))
		decoder.DisallowUnknownFields()
		if decoder.Decode(&request) != nil || len(request.Packets) == 0 || len(request.Packets) > 128 {
			http.Error(w, "invalid request", 400)
			return
		}
		key, err := hex.DecodeString(request.Key)
		if err != nil {
			http.Error(w, "invalid key", 400)
			return
		}
		salt, err := hex.DecodeString(request.Salt)
		if err != nil {
			http.Error(w, "invalid salt", 400)
			return
		}
		profile := srtp.ProtectionProfile(request.Profile)
		if profile != srtp.ProtectionProfileAes128CmHmacSha1_80 && profile != srtp.ProtectionProfileAeadAes128Gcm && profile != srtp.ProtectionProfileAeadAes256Gcm {
			http.Error(w, "unsupported profile", 400)
			return
		}
		options := []srtp.ContextOption{srtp.SRTPReplayProtection(64), srtp.SRTCPReplayProtection(64)}
		if request.AuthOnly {
			options = append(options, srtp.SRTCPNoEncryption())
		}
		peer, err := srtp.CreateContext(key, salt, profile, options...)
		if err != nil {
			http.Error(w, "invalid context", 400)
			return
		}
		results := make([]string, 0, len(request.Packets))
		for _, encoded := range request.Packets {
			packet, err := hex.DecodeString(encoded)
			if err != nil || len(packet) > 4120 {
				http.Error(w, "invalid packet", 400)
				return
			}
			var result []byte
			if request.Rtcp {
				if request.Decrypt {
					result, err = peer.DecryptRTCP(nil, packet, nil)
				} else {
					result, err = peer.EncryptRTCP(nil, packet, nil)
				}
			} else {
				if request.Decrypt {
					result, err = peer.DecryptRTP(nil, packet, nil)
				} else {
					result, err = peer.EncryptRTP(nil, packet, nil)
				}
			}
			if err != nil {
				log.Printf("SRTP peer rejected profile=%d rtcp=%v decrypt=%v bytes=%d: %v", request.Profile, request.Rtcp, request.Decrypt, len(packet), err)
				http.Error(w, "packet rejected", 400)
				return
			}
			results = append(results, hex.EncodeToString(result))
		}
		w.Header().Set("Content-Type", "application/json")
		json.NewEncoder(w).Encode(results)
	})
}

// Reproducible public synthetic known-answer fixtures, generated by Pion.
func writeSrtpVectors(output io.Writer) {
	for _, profile := range []srtp.ProtectionProfile{srtp.ProtectionProfileAes128CmHmacSha1_80, srtp.ProtectionProfileAeadAes128Gcm, srtp.ProtectionProfileAeadAes256Gcm} {
		keyLength, _ := profile.KeyLen()
		saltLength, _ := profile.SaltLen()
		key, salt := make([]byte, keyLength), make([]byte, saltLength)
		for i := range key {
			key[i] = byte(i + 1)
		}
		for i := range salt {
			salt[i] = byte(i + 61)
		}
		peer, err := srtp.CreateContext(key, salt, profile)
		if err != nil {
			panic(err)
		}
		rtpPacket, _ := hex.DecodeString("806f00011234567821324354010203040506070809")
		rtcpPacket, _ := hex.DecodeString("80c80006213243541234567812345678876543210000000400000005")
		rtpProtected, err := peer.EncryptRTP(nil, rtpPacket, nil)
		if err != nil {
			panic(err)
		}
		rtcpProtected, err := peer.EncryptRTCP(nil, rtcpPacket, nil)
		if err != nil {
			panic(err)
		}
		authPeer, err := srtp.CreateContext(key, salt, profile, srtp.SRTCPNoEncryption())
		if err != nil {
			panic(err)
		}
		authOnly, err := authPeer.EncryptRTCP(nil, rtcpPacket, nil)
		if err != nil {
			panic(err)
		}
		json.NewEncoder(output).Encode(map[string]any{"profile": uint16(profile), "rtp": hex.EncodeToString(rtpProtected), "rtcp": hex.EncodeToString(rtcpProtected), "authOnly": hex.EncodeToString(authOnly)})
	}
}
