using System.Net;
using System.Text;
using tryAGI.WebRTC;

internal static class TurnTests
{
    private static void Check(bool value) { if(!value) throw new InvalidOperationException("TURN protocol assertion failed"); }
    // Independently generated by Python struct/hashlib/hmac/binascii from authored synthetic inputs.
    private static byte[] Key()=>Convert.FromHexString("e4e86d00226eb9ad13778007584455ef4dfa36553e523b6e5d3802c13748da76");
    private static byte[] Vector()=>Convert.FromHexString("000300742112a442000102030405060708090a0b00190004110000000006000e73796e7468657469632d7573657200000014000f73796e7468657469632e6c6f63616c000015000a6e6f6e63652d746573740000001d000400020000001c002012fe61571924f6d8f1720b175b7e502031bed4900fe424bedaf68c97408465d7802800045e8133f4");
    internal static void Integrity()
    {
        var vector=Vector(); var key=Key();
        Check(StunMessage.TryParse(vector,out var message) && message.VerifyMessageIntegritySha256(key) && message.VerifyFingerprint());
        Check(!message.VerifyMessageIntegritySha1(key));
        var buffer=new byte[vector.Length]; var writer=new StunMessageWriter(buffer,3,Enumerable.Range(0,12).Select(i=>(byte)i).ToArray());
        Check(writer.TryAddUInt32(0x0019,17u<<24)); Check(writer.TryAddAttribute(0x0006,"synthetic-user"u8));
        Check(writer.TryAddAttribute(0x0014,"synthetic.local"u8)); Check(writer.TryAddAttribute(0x0015,"nonce-test"u8));
        Check(writer.TryAddUInt32(0x001D,2u<<16)); Check(writer.TryComplete(key,true,out var size,true));
        Check(size==vector.Length && buffer.AsSpan().SequenceEqual(vector));
        for(var i=0;i<vector.Length-8;i++) { var changed=vector.ToArray(); changed[i]^=1; Check(!StunMessage.TryParse(changed,out var altered) || !altered.VerifyMessageIntegritySha256(key)); }
        key[0]^=1; Check(!message.VerifyMessageIntegritySha256(key));
    }
    internal static void Bounds()
    {
        var vector=Vector();
        for(var n=0;n<vector.Length;n++) Check(!StunMessage.TryParse(vector.AsSpan(0,n),out _));
        var small=new byte[20+35]; var writer=new StunMessageWriter(small,3,new byte[12]);
        Check(!writer.TryAddAttribute(StunMessage.MessageIntegritySha256,new byte[32]));
        Check(!writer.TryComplete(Key(),false,out _,true));
        var full=new byte[128]; writer=new(full,3,new byte[12]);
        Check(writer.TryAddAttribute(StunMessage.MessageIntegritySha256,new byte[32])==false);
        Check(writer.TryComplete(Key(),false,out var size,true)); Check(!writer.TryComplete(Key(),false,out _,true));
        var duplicated=full.AsSpan(0,size).ToArray().Concat(full.AsSpan(20,36).ToArray()).ToArray();
        System.Buffers.Binary.BinaryPrimitives.WriteUInt16BigEndian(duplicated.AsSpan(2),(ushort)(duplicated.Length-20));
        Check(StunMessage.TryParse(duplicated,out var message) && !message.VerifyMessageIntegritySha256(Key()));
    }
    internal static void Addresses()
    {
        foreach(var ipv6 in new[]{false,true}) foreach(var type in new ushort[]{0x0012,0x0016,0x0020})
        {
            var buffer=new byte[128]; var writer=new StunMessageWriter(buffer,3,Enumerable.Range(0,12).Select(i=>(byte)i).ToArray());
            var endpoint=new IPEndPoint(ipv6?IPAddress.Parse("2001:db8::1234"):IPAddress.Parse("192.0.2.17"),49152);
            Check(writer.TryAddXorAddress(type,endpoint)); Check(writer.TryComplete([],true,out var size));
            Check(StunMessage.TryParse(buffer.AsSpan(0,size),out var message) && message.TryGetXorEndpoint(type,out var decoded) && endpoint.Equals(decoded));
            Check(!message.TryGetXorEndpoint(0x7777,out _));
        }
    }
}
